import Header from "./components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/rgm1dlw.css" />
      </head>
      <body className="font-[sofia-pro,_sans-serif] font-medium not-italic text-slate-100/70 antialiased">
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
